// Generated by Simplified C Transpiler
#include <stdio.h>
#include <gc.h>

typedef struct Player Player;

struct Player {
    int hp;
};

void Player_init(Player* this, int initial_hp) {
    this->hp = initial_hp;
}

void Player_take_damage(Player* this, int amount) {
    this->hp = (this->hp - amount);
}

int main() {
    GC_INIT();
    Player* p = (Player*) GC_MALLOC(sizeof(Player));
    Player_init(p, 40);
    Player_take_damage(p, 20);
    if ((p->hp < 30)) {
        printf("%d\n", 1);
    } else {
        printf("%d\n", 0);
    }
    printf("%d\n", p->hp);
    return 0;
}
