// Generated by Simplified C Transpiler
#include <stdio.h>
#include <string.h>
#include <gc.h>

typedef struct Player Player;

struct Player {
    const char* name;
    int hp;
};

void Player_init(Player* this, const char* hero_name, int initial_hp) {
    this->name = hero_name;
    this->hp = initial_hp;
}

void Player_take_damage(Player* this, int amount) {
    this->hp = (this->hp - amount);
}

void Player_status(Player* this) {
    printf("%s\n", this->name);
    if ((this->hp <= 0)) {
        printf("%s\n", "Status: DEFEATED");
    } else {
        if ((this->hp == 100)) {
            printf("%s\n", "Status: FULL HEALTH");
        } else {
            printf("%s\n", "Status: IN BATTLE");
        }
    }
    printf("%d\n", this->hp);
}

int main() {
    GC_INIT();
    Player* hero = (Player*) GC_MALLOC(sizeof(Player));
    Player_init(hero, "Arthur", 100);
    Player_status(hero);
    Player_take_damage(hero, 60);
    Player_status(hero);
    Player_take_damage(hero, 50);
    Player_status(hero);
    return 0;
}
