// Generated by Simplified C Transpiler
#include <stdio.h>
#include <gc.h>

typedef struct Player Player;

struct Player {
    int hp;
};

void Player_heal(Player* this, int amount) {
    this->hp = (this->hp + amount);
}

int main() {
    GC_INIT();
    Player* p = (Player*) GC_MALLOC(sizeof(Player));
    p->hp = 50;
    while ((p->hp < 100)) {
        Player_heal(p, 10);
    }
    return p->hp;
}
