// Generated by Simplified C Transpiler
#include <stdio.h>
#include <gc.h>

typedef struct Player Player;

struct Player {
    int hp;
};

void Player_heal(Player* this, int amount) {
    this->hp = (this->hp + amount);
}

int main() {
    GC_INIT();
    int i = 0;
    while ((i < 2000000)) {
        Player* temp = (Player*) GC_MALLOC(sizeof(Player));
        temp->hp = i;
        i = (i + 1);
    }
    Player* survivor = (Player*) GC_MALLOC(sizeof(Player));
    survivor->hp = 777;
    printf("%d\n", survivor->hp);
    return 0;
}
