// Generated by myc Compiler (VTable Dynamic Dispatch)
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gc.h>

typedef struct Entity Entity;
typedef struct Entity_VTable Entity_VTable;
typedef struct Warrior Warrior;
typedef struct Warrior_VTable Warrior_VTable;

void Entity_take_damage(Entity* this, int amount);
void Warrior_take_damage(Warrior* this, int amount);

struct Entity_VTable {
    void (*take_damage)(Entity* this, int amount);
};

struct Warrior_VTable {
    void (*take_damage)(Entity* this, int amount);
};

struct Entity {
    const Entity_VTable* vptr;
    const char* name;
    int hp;
};

struct Warrior {
    Entity base;
    int armor;
};

static const Entity_VTable __vtable_Entity = {
    .take_damage = (void (*)(Entity*, int)) Entity_take_damage,
};

static const Warrior_VTable __vtable_Warrior = {
    .take_damage = (void (*)(Entity*, int)) Warrior_take_damage,
};

typedef struct { int length; int data[]; } Array_int;
typedef struct { int length; const char* data[]; } Array_string;
typedef struct { int length; Entity* data[]; } Array_Entity;
typedef struct { int length; Warrior* data[]; } Array_Warrior;

static void __bounds_check(int index, int length) {
    if (index < 0 || index >= length) {
        fprintf(stderr, "Error: Array index %d out of bounds (length %d)\n", index, length);
        exit(1);
    }
}

static Array_int* __new_Array_int(int len) {
    Array_int* a = (Array_int*) GC_MALLOC(sizeof(Array_int) + len * sizeof(int));
    a->length = len;
    return a;
}

static Array_string* __new_Array_string(int len) {
    Array_string* a = (Array_string*) GC_MALLOC(sizeof(Array_string) + len * sizeof(const char*));
    a->length = len;
    return a;
}

static Array_Entity* __new_Array_Entity(int len) {
    Array_Entity* a = (Array_Entity*) GC_MALLOC(sizeof(Array_Entity) + len * sizeof(Entity*));
    a->length = len;
    return a;
}

static Array_Warrior* __new_Array_Warrior(int len) {
    Array_Warrior* a = (Array_Warrior*) GC_MALLOC(sizeof(Array_Warrior) + len * sizeof(Warrior*));
    a->length = len;
    return a;
}

void Entity_init(Entity* this, const char* n, int h) {
    ((Entity*) this)->vptr = (const Entity_VTable*) &__vtable_Entity;
    this->name = n;
    this->hp = h;
}

static Entity* __new_Entity(const char* n, int h) {
    Entity* this = (Entity*) GC_MALLOC(sizeof(Entity));
    Entity_init(this, n, h);
    return this;
}

void Warrior_init(Warrior* this, const char* n, int h, int a) {
    ((Entity*) this)->vptr = (const Entity_VTable*) &__vtable_Warrior;
    ((Entity*) this)->name = n;
    ((Entity*) this)->hp = h;
    this->armor = a;
}

static Warrior* __new_Warrior(const char* n, int h, int a) {
    Warrior* this = (Warrior*) GC_MALLOC(sizeof(Warrior));
    Warrior_init(this, n, h, a);
    return this;
}

void Entity_take_damage(Entity* this, int amount) {
    this->hp = (this->hp - amount);
    printf("%s\n", "Base Entity damaged:");
    printf("%d\n", this->hp);
}

void Warrior_take_damage(Warrior* this, int amount) {
    int reduced = (amount - 5);
    ((Entity*) this)->hp = (((Entity*) this)->hp - reduced);
    printf("%s\n", "Warrior armor absorbed damage:");
    printf("%d\n", ((Entity*) this)->hp);
}

int main() {
    GC_INIT();
    Entity* e1 = __new_Entity("Generic", 100);
    ((const Entity_VTable*) ((Entity*) e1)->vptr)->take_damage((Entity*) e1, 30);
    Entity* e2 = (Entity*) __new_Warrior("Conan", 100, 20);
    ((const Entity_VTable*) ((Entity*) e2)->vptr)->take_damage((Entity*) e2, 30);
    if ((e2->hp == 75)) {
        printf("%s\n", "Polymorphic dispatch success!");
    }
    return 0;
}
