// Generated by myc Compiler
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gc.h>

typedef struct Entity Entity;
typedef struct Warrior Warrior;

typedef struct { int length; int data[]; } Array_int;
typedef struct { int length; const char* data[]; } Array_string;
typedef struct { int length; Entity* data[]; } Array_Entity;
typedef struct { int length; Warrior* data[]; } Array_Warrior;

static void __bounds_check(int index, int length) {
    if (index < 0 || index >= length) {
        fprintf(stderr, "Error: Array index %d out of bounds (length %d)\n", index, length);
        exit(1);
    }
}

static Array_int* __new_Array_int(int len) {
    Array_int* a = (Array_int*) GC_MALLOC(sizeof(Array_int) + len * sizeof(int));
    a->length = len;
    return a;
}

static Array_string* __new_Array_string(int len) {
    Array_string* a = (Array_string*) GC_MALLOC(sizeof(Array_string) + len * sizeof(const char*));
    a->length = len;
    return a;
}

static Array_Entity* __new_Array_Entity(int len) {
    Array_Entity* a = (Array_Entity*) GC_MALLOC(sizeof(Array_Entity) + len * sizeof(Entity*));
    a->length = len;
    return a;
}

static Array_Warrior* __new_Array_Warrior(int len) {
    Array_Warrior* a = (Array_Warrior*) GC_MALLOC(sizeof(Array_Warrior) + len * sizeof(Warrior*));
    a->length = len;
    return a;
}

struct Entity {
    const char* name;
    int hp;
};

struct Warrior {
    Entity base;
    int armor;
};

void Entity_init(Entity* this, const char* entity_name, int initial_hp) {
    this->name = entity_name;
    this->hp = initial_hp;
}

void Entity_take_damage(Entity* this, int amount) {
    this->hp = (this->hp - amount);
}

void Warrior_init(Warrior* this, const char* warrior_name, int initial_hp, int initial_armor) {
    ((Entity*) this)->name = warrior_name;
    ((Entity*) this)->hp = initial_hp;
    this->armor = initial_armor;
}

void Warrior_defend(Warrior* this) {
    this->armor = (this->armor + 5);
}

int main() {
    GC_INIT();
    printf("%s\n", "=== TEST 1: INHERITANCE & SUBTYPING ===");
    Warrior* w = (Warrior*) GC_MALLOC(sizeof(Warrior));
    Warrior_init(w, "Conan", 100, 20);
    printf("%s\n", ((Entity*) w)->name);
    Entity_take_damage((Entity*) w, 30);
    printf("%d\n", ((Entity*) w)->hp);
    Warrior_defend(w);
    printf("%d\n", w->armor);
    Entity* e = (Entity*) w;
    Entity_take_damage(e, 20);
    printf("%d\n", ((Entity*) w)->hp);
    printf("%s\n", "=== TEST 2: GC ARRAYS & LENGTH ===");
    Array_int* scores = __new_Array_int(3);
    __bounds_check(0, scores->length);
    scores->data[0] = 88;
    __bounds_check(1, scores->length);
    scores->data[1] = 92;
    __bounds_check(2, scores->length);
    scores->data[2] = 99;
    printf("%d\n", scores->length);
    printf("%d\n", (__bounds_check(0, scores->length), scores->data[0]));
    printf("%d\n", (__bounds_check(1, scores->length), scores->data[1]));
    printf("%d\n", (__bounds_check(2, scores->length), scores->data[2]));
    Array_Warrior* army = __new_Array_Warrior(2);
    __bounds_check(0, army->length);
    army->data[0] = w;
    __bounds_check(1, army->length);
    army->data[1] = (Warrior*) GC_MALLOC(sizeof(Warrior));
    Warrior_init(((Warrior*) army->data[1]), "Thor", 150, 40);
    printf("%s\n", ((Entity*) (__bounds_check(1, army->length), army->data[1]))->name);
    printf("%s\n", "=== TEST 3: BOOLEANS & SHORT-CIRCUITING ===");
    int alive = 1;
    int shielded = 0;
    if (((alive && (!shielded)) || (((Entity*) w)->hp <= 0))) {
        printf("%s\n", "Combat condition passed!");
    } else {
        printf("%s\n", "Combat condition failed!");
    }
    return 0;
}
