// Generated by myc Compiler
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gc.h>

static void gc_collect(void) { GC_gcollect(); }
static int gc_heap_size(void) { return (int) GC_get_heap_size(); }
static int gc_free_bytes(void) { return (int) GC_get_free_bytes(); }

static const char* __str_concat(const char* a, const char* b) {
    size_t la = strlen(a);
    size_t lb = strlen(b);
    char* res = (char*) GC_MALLOC_ATOMIC(la + lb + 1);
    memcpy(res, a, la);
    memcpy(res + la, b, lb);
    res[la + lb] = '\0';
    return res;
}

static const char* __str_concat_int(const char* a, int b) {
    char buf[32];
    int len = snprintf(buf, sizeof(buf), "%d", b);
    size_t la = strlen(a);
    char* res = (char*) GC_MALLOC_ATOMIC(la + len + 1);
    memcpy(res, a, la);
    memcpy(res + la, buf, len);
    res[la + len] = '\0';
    return res;
}

static const char* __int_concat_str(int a, const char* b) {
    char buf[32];
    int len = snprintf(buf, sizeof(buf), "%d", a);
    size_t lb = strlen(b);
    char* res = (char*) GC_MALLOC_ATOMIC(len + lb + 1);
    memcpy(res, buf, len);
    memcpy(res + len, b, lb);
    res[len + lb] = '\0';
    return res;
}

typedef struct { int length; int data[]; } Array_int;
typedef struct { int length; const char* data[]; } Array_string;

static void __bounds_check(int index, int length) {
    if (index < 0 || index >= length) {
        fprintf(stderr, "Error: Array index %d out of bounds (length %d)\n", index, length);
        exit(1);
    }
}

static Array_int* __new_Array_int(int len) {
    Array_int* a = (Array_int*) GC_MALLOC(sizeof(Array_int) + len * sizeof(int));
    a->length = len;
    return a;
}

static Array_string* __new_Array_string(int len) {
    Array_string* a = (Array_string*) GC_MALLOC(sizeof(Array_string) + len * sizeof(const char*));
    a->length = len;
    return a;
}

int main() {
    GC_INIT();
    Array_int* nums = __new_Array_int(5);
    for (int i = 0; (i < 5); i = (i + 1)) {
        __bounds_check(i, nums->length);
        nums->data[i] = ((i + 1) * 2);
    }
    int sum = 0;
    for (int j = 0; (j < nums->length); j = (j + 1)) {
        if (((__bounds_check(j, nums->length), nums->data[j]) == 10)) {
            continue;
        }
        sum = (sum + (__bounds_check(j, nums->length), nums->data[j]));
    }
    printf("%s\n", __str_concat_int("Evens sum: ", sum));
    for (int k = 0; (k < 20); k = (k + 1)) {
        if ((k == 7)) {
            printf("%s\n", __str_concat_int("Break reached at: ", k));
            break;
        }
    }
    int initial_heap = gc_heap_size();
    if ((initial_heap > 0)) {
        printf("%s\n", "Heap size before collect is valid");
    }
    gc_collect();
    printf("%s\n", "GC collection cycle finished");
    return 0;
}
