// Generated by myc Compiler (VTable Dynamic Dispatch + GC Strings)
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <gc.h>

static const char* __str_concat(const char* a, const char* b) {
    size_t la = strlen(a);
    size_t lb = strlen(b);
    char* res = (char*) GC_MALLOC_ATOMIC(la + lb + 1);
    memcpy(res, a, la);
    memcpy(res + la, b, lb);
    res[la + lb] = '\0';
    return res;
}

static const char* __str_concat_int(const char* a, int b) {
    char buf[32];
    int len = snprintf(buf, sizeof(buf), "%d", b);
    size_t la = strlen(a);
    char* res = (char*) GC_MALLOC_ATOMIC(la + len + 1);
    memcpy(res, a, la);
    memcpy(res + la, buf, len);
    res[la + len] = '\0';
    return res;
}

static const char* __int_concat_str(int a, const char* b) {
    char buf[32];
    int len = snprintf(buf, sizeof(buf), "%d", a);
    size_t lb = strlen(b);
    char* res = (char*) GC_MALLOC_ATOMIC(len + lb + 1);
    memcpy(res, buf, len);
    memcpy(res + len, b, lb);
    res[len + lb] = '\0';
    return res;
}

typedef struct { int length; int data[]; } Array_int;
typedef struct { int length; const char* data[]; } Array_string;

static void __bounds_check(int index, int length) {
    if (index < 0 || index >= length) {
        fprintf(stderr, "Error: Array index %d out of bounds (length %d)\n", index, length);
        exit(1);
    }
}

static Array_int* __new_Array_int(int len) {
    Array_int* a = (Array_int*) GC_MALLOC(sizeof(Array_int) + len * sizeof(int));
    a->length = len;
    return a;
}

static Array_string* __new_Array_string(int len) {
    Array_string* a = (Array_string*) GC_MALLOC(sizeof(Array_string) + len * sizeof(const char*));
    a->length = len;
    return a;
}

int main() {
    GC_INIT();
    const char* greeting = __str_concat("Hello, ", "Arthur!");
    printf("%s\n", greeting);
    int hp = 75;
    const char* status = __str_concat(__str_concat_int("Player health: ", hp), " HP");
    printf("%s\n", status);
    int sec = 10;
    const char* countdown = __str_concat(__str_concat_int("Countdown: ", sec), " seconds remaining");
    printf("%s\n", countdown);
    const char* name = "Conan";
    int lvl = 42;
    int max_hp = 100;
    const char* chained = __str_concat(__str_concat_int(__str_concat(__str_concat_int(__str_concat(__str_concat("Chained: ", name), " level "), lvl), " with "), max_hp), " HP!");
    printf("%s\n", chained);
    int i = 0;
    const char* temp = "";
    while ((i < 1000)) {
        temp = __str_concat_int("iteration_", i);
        i = (i + 1);
    }
    printf("%s\n", __str_concat("Loop string: ", temp));
    return 0;
}
